window.ORKEN_KB=[
 {keys:["what is orken","orken ai kya","orken ai kia","orken"],en:"Orken AI is an AI engineering and automation company. It builds production AI agents and end-to-end workflows for support, sales, operations, RAG, voice, and internal copilots.",ur:"Orken AI aik AI engineering aur automation company hai jo production AI agents aur end-to-end workflows banati hai—support, sales, operations, RAG, voice aur internal copilots ke liye."},
 {keys:["services","what do you build","what does orken offer","services offer"],en:"Orken AI builds voice agents, support bots, sales SDR agents, custom GPTs/internal copilots, RAG systems, and multi-agent orchestration. It also connects agents with tools such as n8n, CRM and support platforms.",ur:"Orken AI voice agents, support bots, sales SDR agents, custom GPTs/internal copilots, RAG systems aur multi-agent orchestration banata hai. Agents ko n8n, CRM aur support platforms ke sath bhi connect kiya ja sakta hai."},
 {keys:["price","pricing","cost","how much"],en:"The public Orken AI pricing page currently lists specialized AI workforce subscriptions at $49/month for several agents. Its FAQ also says custom projects commonly fall in the $10k–$25k range for a single agent and $25k–$50k for multi-agent/RAG implementations. Pricing can vary by scope.",ur:"Orken AI ki public pricing page par kai specialized AI workforce agents $49/month listed hain. FAQ ke mutabiq custom single-agent projects aam tor par $10k–$25k aur multi-agent/RAG implementations $25k–$50k range mein hoti hain. Exact price scope par depend karta hai."},
 {keys:["how long","timeline","days","weeks","kitna time"],en:"Orken AI says most custom agents ship in about 21–28 days. Its four-week process is discovery/evals, build/integration, shadow mode, then production rollout.",ur:"Orken AI ke mutabiq zyada tar custom agents takreeban 21–28 din mein ship hote hain. Four-week process mein discovery/evals, build/integration, shadow mode aur phir production rollout hota hai."},
 {keys:["model","which model","claude","gpt","llama"],en:"Orken AI says model choice depends on the workload. Its public materials mention Claude, GPT-4o and Llama 3.1, with different models used for support, voice, vision and data-residency needs.",ur:"Orken AI ke mutabiq model workload ke hisaab se select hota hai. Public information mein Claude, GPT-4o aur Llama 3.1 ka zikr hai; support, voice, vision aur data-residency needs ke mutabiq model change ho sakta hai."},
 {keys:["privacy","data privacy","data safe","nda"],en:"Orken AI's public privacy information says it can deploy regulated-industry systems on-premises or in the customer's cloud account, and its FAQ says NDAs are signed before discovery calls.",ur:"Orken AI ki public information ke mutabiq regulated industries ke systems on-premises ya customer ke cloud account mein deploy kiye ja sakte hain, aur FAQ mein discovery calls se pehle NDA ka zikr hai."},
 {keys:["integrations","integration","n8n","hubspot","zendesk","pinecone","twilio"],en:"Orken AI lists integrations and technologies including n8n, Make, Pinecone, Vapi, HubSpot, Slack, Zendesk, Supabase, Twilio and other REST/SQL/GraphQL connectors.",ur:"Orken AI n8n, Make, Pinecone, Vapi, HubSpot, Slack, Zendesk, Supabase, Twilio aur REST/SQL/GraphQL connectors jaisi technologies/integrations use karta hai."},
 {keys:["voice agent","voice","call"],en:"Orken AI offers voice agents for inbound and outbound calls. Its public site describes voice agents with natural turn-taking and CRM logging, using a voice stack that includes Vapi, Twilio and ElevenLabs.",ur:"Orken AI inbound aur outbound calls ke liye voice agents offer karta hai. Public site ke mutabiq voice stack mein Vapi, Twilio aur ElevenLabs shamil hain."},
 {keys:["hello","hi","salam","assalam"],en:"Hello! I can answer questions about Orken AI, including services, AI agents, pricing, process, integrations, voice agents and privacy.",ur:"Assalam-o-alaikum! Main Orken AI ke services, AI agents, pricing, process, integrations, voice agents aur privacy ke bare mein jawab de sakta hoon."}
];